# Generated by Django 5.2.1 on 2025-05-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('taskmanager', '0001_initial'), ('taskmanager', '0002_alter_users_id'), ('taskmanager', '0003_alter_users_id'), ('taskmanager', '0004_alter_users_id'), ('taskmanager', '0005_alter_users_email'), ('taskmanager', '0006_task_delete_users'), ('taskmanager', '0007_remove_task_deleted_at'), ('taskmanager', '0008_task_deleted_at')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(default=None)),
            ],
        ),
    ]
