# Generated by Django 5.2.1 on 2025-05-23 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager', '0008_task_deleted_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='deleted_at',
        ),
    ]
